name: Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: HurricanKai/Publish-Docker-Github-Action@master
        with:
          name: mkhizeryounas/express
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GH_PERSONAL_TOKEN }}
          registry: docker.pkg.github.com
      - name: Run deployment with dropspot
        run: |
          npm i dropspot-cli@latest
          npx dropspot deploy -u $DROPSPOT_SERVER -t $DROPSPOT_DEPLOYMENT_TOKEN

        env:
          CI: true
          DROPSPOT_SERVER: ${{ secrets.DROPSPOT_SERVER }}
          DROPSPOT_DEPLOYMENT_TOKEN: ${{ secrets.DROPSPOT_DEPLOYMENT_TOKEN_GITHUB }}
